import { IconProps } from "vuetify";
import {
   IconAdjustments,
   IconAlertSquareRoundedFilled,
   IconArrowBigUp,
   IconArrowDown,
   IconArrowLeft,
   IconArrowRight,
   IconArrowsMaximize,
   IconArrowsMinimize,
   IconArrowUp,
   IconBackspace,
   IconBell,
   IconBolt,
   IconBrandGoogleMaps,
   IconBrandInstagram,
   IconBrowser,
   IconBuildings,
   IconBuildingWarehouse,
   IconCalendar,
   IconCaretDownFilled,
   IconCaretRightFilled,
   IconCash,
   IconCheck,
   IconChevronCompactUp,
   IconChevronDown,
   IconChevronLeft,
   IconChevronLeftPipe,
   IconChevronRight,
   IconChevronRightPipe,
   IconChevronUp,
   IconCircle,
   IconCircleCheckFilled,
   IconCircleDotFilled,
   IconCircleFilled,
   IconCircleX,
   IconCloudUpload,
   IconColorPicker,
   IconCommand,
   IconCopy,
   IconCrop11,
   IconCrop169,
   IconCrop32,
   IconCrop75,
   IconCurrencyLira,
   IconDeviceFloppy,
   IconDeviceIpadHorizontal,
   IconDeviceIpadHorizontalQuestion,
   IconDevicesPc,
   IconDotsVertical,
   IconEye,
   IconEyeDown,
   IconEyeOff,
   IconEyeUp,
   IconGraph,
   IconGripVertical,
   IconHeartHandshake,
   IconHome,
   IconInfoSquareRoundedFilled,
   IconLanguage,
   IconLayoutGridAdd,
   IconLicense,
   IconLink,
   IconListCheck,
   IconListDetails,
   IconLogin,
   IconLogout,
   IconMail,
   IconMap,
   IconMapPin,
   IconMaximize,
   IconMenu2,
   IconMinimize,
   IconMinus,
   IconMoonStars,
   IconPalette,
   IconPaperclip,
   IconPencil,
   IconPercentage,
   IconPhone,
   IconPhoto,
   IconPhotoPlus,
   IconPlayerPauseFilled,
   IconPlayerPlayFilled,
   IconPlus,
   IconPrinter,
   IconQuestionMark,
   IconRefresh,
   IconRepeat,
   IconReplace,
   IconResize,
   IconRotate2,
   IconRotateClockwise2,
   IconRuler2,
   IconSearch,
   IconSelector,
   IconSettings,
   IconShare,
   IconSlash,
   IconSortAscending,
   IconSortDescending,
   IconSpace,
   IconSparkles,
   IconSquareFilled,
   IconSquareRounded,
   IconSquareRoundedCheckFilled,
   IconSquareRoundedMinusFilled,
   IconStar,
   IconStarFilled,
   IconStarHalfFilled,
   IconSun,
   IconTag,
   IconTagPlus,
   IconTags,
   IconTarget,
   IconTextPlus,
   IconTie,
   IconTools,
   IconTransferVertical,
   IconTrash,
   IconUser,
   IconUsers,
   IconViewportTall,
   IconViewportWide,
   IconVolume,
   IconVolume2,
   IconVolume3,
   IconVolumeOff,
   IconWallet,
   IconWorldWww,
   IconX
} from "@tabler/icons-vue";

export const tablerAliases = {
   // vuetify start
   collapse: IconChevronUp,
   complete: IconCheck,
   cancel: IconCircleX,
   close: IconX,
   delete: IconCircleX,
   clear: IconX,
   success: IconCircleCheckFilled,
   info: IconInfoSquareRoundedFilled,
   warning: IconAlertSquareRoundedFilled,
   error: IconCircleX,
   prev: IconChevronLeft,
   next: IconChevronRight,
   checkboxOn: IconSquareRoundedCheckFilled,
   checkboxOff: IconSquareRounded,
   checkboxIndeterminate: IconSquareRoundedMinusFilled,
   delimiter: IconCircleFilled,
   sortAsc: IconSortAscending,
   sortDesc: IconSortDescending,
   expand: IconChevronDown,
   menu: IconMenu2,
   subgroup: IconCaretDownFilled,
   dropdown: IconCaretDownFilled,
   radioOn: IconCircleDotFilled,
   radioOff: IconCircle,
   edit: IconPencil,
   ratingEmpty: IconStar,
   ratingFull: IconStarFilled,
   ratingHalf: IconStarHalfFilled,
   loading: IconRefresh,
   first: IconChevronLeftPipe,
   last: IconChevronRightPipe,
   unfold: IconSelector,
   file: IconPaperclip,
   plus: IconPlus,
   minus: IconMinus,
   calendar: IconCalendar,
   treeviewCollapse: IconCaretDownFilled,
   treeviewExpand: IconCaretRightFilled,
   eyeDropper: IconColorPicker,
   upload: IconCloudUpload,
   color: IconPalette,
   command: IconCommand,
   ctrl: IconChevronCompactUp,
   space: IconSpace,
   shift: IconArrowBigUp,
   alt: IconTransferVertical,
   enter: IconLogin,
   arrowup: IconArrowUp,
   arrowdown: IconArrowDown,
   arrowleft: IconArrowLeft,
   arrowright: IconArrowRight,
   backspace: IconBackspace,
   play: IconPlayerPlayFilled,
   pause: IconPlayerPauseFilled,
   fullscreen: IconMaximize,
   fullscreenExit: IconMinimize,
   volumeHigh: IconVolume,
   volumeMedium: IconVolume2,
   volumeLow: IconVolume3,
   volumeOff: IconVolumeOff,
   // vuetify end

   sparkles: IconSparkles,
   save: IconDeviceFloppy,
   question: IconQuestionMark,
   exclamation: IconAlertSquareRoundedFilled,
   percent: IconPercentage,
   notification: IconBell,
   slash: IconSlash,
   search: IconSearch,
   dots: IconDotsVertical,
   translate: IconLanguage,
   settings: IconSettings,
   definitions: IconAdjustments,
   trash: IconTrash,
   copy: IconCopy,
   ruler: IconRuler2,
   link: IconLink,
   reset: IconRefresh,
   user: IconUser,
   userGroup: IconUsers,
   login: IconLogin,
   logout: IconLogout,
   moon: IconMoonStars,
   sun: IconSun,
   tags: IconTags,
   tag: IconTag,
   print: IconPrinter,
   wallet: IconWallet,
   tools: IconTools,
   photo: IconPhoto,
   browser: IconBrowser,
   target: IconTarget,
   handShake: IconHeartHandshake,
   replace: IconReplace,
   graph: IconGraph,
   task: IconListCheck,
   company: IconBuildings,
   detail: IconListDetails,
   gridAdd: IconLayoutGridAdd,
   tie: IconTie,
   map: IconMap,
   mapPin: IconMapPin,
   equipment: IconDevicesPc,
   license: IconLicense,
   subscription: IconRepeat,
   share: IconShare,
   dotsVertical: IconGripVertical,
   eyeOn: IconEye,
   eyeOff: IconEyeOff,
   eyeDown: IconEyeDown,
   eyeUp: IconEyeUp,
   listAdd: IconTextPlus,
   imageAdd: IconPhotoPlus,
   crop11: IconCrop11,
   crop32: IconCrop32,
   crop75: IconCrop75,
   crop169: IconCrop169,
   resize: IconResize,
   viewportWide: IconViewportWide,
   viewportTall: IconViewportTall,
   rotateLeft: IconRotate2,
   rotateRight: IconRotateClockwise2,
   imageFill: IconArrowsMaximize,
   imageFit: IconArrowsMinimize,
   tagPlus: IconTagPlus,
   square: IconSquareFilled,
   bolt: IconBolt,
   www: IconWorldWww,
   instagram: IconBrandInstagram,
   googleMaps: IconBrandGoogleMaps,
   phone: IconPhone,
   mail: IconMail,
   cash: IconCash,

   // app
   home: IconHome,
   warehouse: IconBuildingWarehouse,
   product: IconDeviceIpadHorizontal,
   productQuestion: IconDeviceIpadHorizontalQuestion,

   // currency
   try: IconCurrencyLira
};

export const tabler = {
   component: (props: IconProps) => {
      return h(props.tag, [h(tablerAliases[props.icon as keyof typeof tablerAliases])]);
   }
};
